apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
  labels:
    app-pace-co/app: {{ include "lake-api.name" . }}
  {{- if .Values.extraLabels }}
  {{- range $key, $value := .Values.extraLabels }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
name: {{ include "lake-api.name" . }}
namespace: '{{ .Values.namespace }}'
spec:
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - backend:
              serviceName: {{ include "lake-api.name" . }}
              servicePort: {{ .Values.service.port }}