{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app-pace-co/app: {{ include "lake-api.name" . }}
    chart: {{ include "lake-api.chart" . }}
  {{- if .Values.extraLabels }}
  {{- range $key, $value := .Values.extraLabels }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  name: {{ .Values.serviceAccount.name }}
  {{- end -}}