apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "lake-api.fullname" . }}-vs
  namespace: {{ .Values.namespace }}
spec:
  gateways:
    - {{ .Values.ingress.gateway }}
  hosts:
    - {{ .Values.ingress.domain }}
  http:
    - match:
        - uri:
            prefix: /v1
      route:
        - destination:
            host: {{ include "lake-api.fullname" . }}
            port:
              number: {{ .Values.service.targetPort }}